name: testmock

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      id: setup
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      id: checkout
      uses: actions/checkout@v2
    
    - name: Cache
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: deps-cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}

    - name: Get dependencies
      id: deps
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      id: build
      run: |
        export GO111MODULE=on
        GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -v -o bin/testmock .

    - name: Test
      run: go test -timeout 30s -v ./...
      
    - name: Tag
      id: tagging
      uses: mathieudutour/github-tag-action@v5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: main

    - name: Release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tagging.outputs.new_tag }}
        release_name: Release ${{ steps.tagging.outputs.new_tag }}
